compressionLevel: mixed
enableTelemetry: false
nodeLinker: node-modules
packageExtensions:
  '@commitlint/load@*':
    dependencies:
      '@types/node': '*'
      typescript: '*'
  '@typescript-eslint/type-utils@*':
    dependencies:
      eslint: '*'
  '@typescript-eslint/utils@*':
    dependencies:
      typescript: '*'
  'typescript-eslint@*':
    dependencies:
      eslint: '*'
supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
