name: Dependabot Auto-merge
on:
  pull_request:
    branches:
      - main
jobs:
  auto_merge:
    name: Auto-merge
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.2.2
      - name: Set Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2.2.0
      - name: Approve and merge pull request
        if: ${{ contains(fromJSON('["version-update:semver-minor", "version-update:semver-patch"]'), steps.dependabot-metadata.outputs.update-type) }}
        run: |
          gh pr checkout "$PULL_REQUEST_URL"

          if [ "$(gh pr status --jq .currentBranch.reviewDecision --json reviewDecision)" != 'APPROVED' ]; then
            gh pr review --approve "$PULL_REQUEST_URL"
          fi

          gh pr merge --auto --squash "$PULL_REQUEST_URL"
        env:
          GH_TOKEN: ${{ github.token }}
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
